$terminal = ghostty
$filemanager = nautilus
$browser = firefox
$mailclient = thunderbird
$spotify = flatpak run com.spotify.Client
$screenlock = hyprlock
$osdclient = swayosd-client --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"
$launcher = rofi -show drun
$runscript = zsh -c
$powermenu = rofi -show p -modi 'p:~/.config/scripts/rofi-power-menu --choices=shutdown/reboot/suspend/logout' -theme-str 'inputbar {enabled: false;}'

exec-once = dunst
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = waybar
exec-once = hyprsunset
exec-once = swayosd-server
exec-once = swaybg -i ~/.config/themes/nord/backgrounds/3-nord.jpg

env = XCURSOR_SIZE,20
env = HYPRCURSOR_SIZE,20

source = ~/.config/hypr/monitors.conf
source = ~/.config/themes/current/hyprland.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/scratchpads.conf

