input {
    kb_layout = us
    kb_variant = altgr-intl

    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    touchpad {
        natural_scroll = true
    }
}
gestures {
    workspace_swipe_distance = 150
    workspace_swipe_cancel_ratio = 0.3
}
gesture = 3, horizontal, workspace

###################
### KEYBINDINGS ###
###################

$mainMod = SUPER # Sets "Windows" key as main modifier

binds {
    hide_special_on_workspace_change = true
}

bindr = $mainMod, Q, exec, $terminal
bindr = $mainMod, B, exec, $browser
bindr = $mainMod, C, killactive,
bindr = $mainMod, E, exec, $filemanager
bindr = $mainMod, V, togglefloating,
bindr = $mainMod, R, exec, $menu
bindr = $mainMod, P, pseudo, # dwindle
bindr = $mainMod, J, togglesplit, # dwindle
bindr = $mainMod, escape, exec, $screenlock
bindr = $mainMod SHIFT, B, exec, .config/scripts/launch-tui bluetui
bindr = $mainMod SHIFT, W, exec, .config/scripts/launch-tui impala
bindr = $mainMod SHIFT, S, exec, .config/scripts/launch-tui wiremix
bindr = $mainMod SHIFT, T, exec, .config/scripts/launch-tui btop
bindr = $mainMod SHIFT, escape, exec, .config/scripts/toggle-waybar
bindr = $mainMod SHIFT, P, exec, .config/scripts/pop-window 875 600
bindr = $mainMod, Super_L, exec, $launcher
bindr = $mainMod, BackSpace, exec, $powermenu

# screenshot 
bind =, Print, exec, grim -g "$(slurp)" - | wl-copy && wl-paste > ~/media/Screenshots/Screenshot-$(date +%F_%T).png 
bind = SHIFT, Print, exec, grim - | wl-copy && wl-paste > ~/media/Screenshots/Screenshot-$(date +%F_%T).png
# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = ALT, mouse:272, resizewindow

# Laptop multimedia keys for volume and LCD brightness (with OSD)
bindeld = ,XF86AudioRaiseVolume, Volume up, exec, $osdclient --output-volume raise
bindeld = ,XF86AudioLowerVolume, Volume down, exec, $osdclient --output-volume lower
bindeld = ,XF86AudioMute, Mute, exec, $osdclient --output-volume mute-toggle
bindeld = SHIFT, XF86AudioMute, Mute microphone, exec, $osdclient --input-volume mute-toggle
bindeld = ,XF86MonBrightnessUp, Brightness up, exec, $osdclient --brightness raise
bindeld = ,XF86MonBrightnessDown, Brightness down, exec, $osdclient --brightness lower
bindd = ,XF86AudioMedia, Enable Caffeine, exec, .config/scripts/caffeine

# Requires playerctl
bindld = , XF86AudioNext, Next track, exec, $osdclient --playerctl next
bindld = , XF86AudioPause, Pause, exec, $osdclient --playerctl play-pause
bindld = , XF86AudioPlay, Play, exec, $osdclient --playerctl play-pause
bindld = , XF86AudioPrev, Previous track, exec, $osdclient --playerctl previous
