windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}
windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# floating window behavior
windowrule = match:tag floating-window, float on
windowrule = match:tag floating-window, center on
windowrule = match:tag floating-window, size 875 600
windowrule = match:tag floating-window, animation slide down

windowrule = match:class tui.*, tag +floating-window
windowrule = match:class (xdg-desktop-portal-gtk|org.gnome.Nautilus), tag +floating-window
windowrule = match:title ^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[C|c]hoose.*), tag +floating-window
windowrule = match:title ^(*Bitwarden*)
layerrule = animation slide, match:namespace rofi 
