# Scratchpads
workspace = special:mail, on-created-empty:$mailclient
windowrule = match:class org.mozilla.Thunderbird, workspace special:mail
bind = $mainMod, M, togglespecialworkspace, mail

workspace = special:spotify, on-created-empty:$spotify
windowrule = match:class Spotify, workspace special:spotify
bind = $mainMod, S, togglespecialworkspace, spotify

workspace = special:term, on-created-empty:$terminal
bind = $mainMod, T, togglespecialworkspace, term
gesture = 3, vertical, special, term
